# 문제1

In [ ]:
#  문제1 : 다음은 1부터 10까지 1차원 배열을 생성하고 배열의 속성을 알아보는 프로그램이다. 실행결과를 보고 빈곳에 가장 알맞은 속성을 쓰시오.
arr=np.arange(1,11)
print(arr)
print('ndim:',arr.ndim)  
print('shape:',arr.shape) 
print('dtype:',arr.dtype) 
print('size:',arr.size) 

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
shape: (10,)
dtype: int64
size: 10


# 문제2

In [2]:
#문제2
#1 값이 10~50인 벡터를 만들고 벡터를 반전시켜 출력해보세요
import numpy as np
arr=np.arange(10,50)
arr=arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [3]:
#2. 랜덤 값이 있는 10x10 배열을 만들고 최대값과 최소값을 찾아보세요
arr=np.random.random((10,10))
max,min=arr.max(),arr.min()
# print(arr)
print(max,min)

[[0.56003573 0.18100081 0.80609359 0.68010423 0.11187144 0.9830375
  0.39016028 0.99848659 0.42123847 0.14612061]
 [0.38261507 0.02483605 0.65162411 0.98995    0.91978803 0.2783857
  0.24316098 0.4706426  0.42933545 0.68067789]
 [0.21110652 0.3490768  0.93292787 0.84403133 0.37268325 0.55662167
  0.12602514 0.79610422 0.63815013 0.57686111]
 [0.68732608 0.81588413 0.61535033 0.98179306 0.68135012 0.25698797
  0.99995739 0.3333871  0.40930152 0.20976975]
 [0.45379031 0.60967683 0.33940343 0.78252137 0.58268225 0.3572979
  0.90376249 0.68018671 0.24330327 0.37692822]
 [0.40347204 0.33922804 0.07263942 0.40340493 0.65958341 0.1954554
  0.50212305 0.94425201 0.62267873 0.70861061]
 [0.50277904 0.56655184 0.85367996 0.50549918 0.19476139 0.27045227
  0.6335057  0.22221845 0.71038105 0.59403056]
 [0.31821832 0.11747759 0.18566538 0.61956532 0.25353581 0.68435443
  0.99997054 0.8838049  0.78822017 0.14271717]
 [0.33808225 0.99843607 0.47960271 0.78445398 0.04310566 0.61836298
  0.32386745 0.4

In [ ]:
#3. 0-8범위위 값을 사용하여 3x3 배열을 생성해보세요
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#4-1. 다음과 같이 1에서 24까지의 값을 가지는 4x6 크기의 2차원 행렬 arr을 생성하세요
arr=np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
#4-2. arr배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하시오.
print(arr[1:3,1:5])

[[ 8  9 10 11]
 [14 15 16 17]]


In [ ]:
#4-3. arr배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하시오.
print(arr[2:,::-1])

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [ ]:
#4-4. arr배열에서 2의 배수만 출력해보자.
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
#4-5. arr배열에서 10부터20까지의 값만 출력해보자.
result=arr[(arr>=10) & (arr<=20)]
result

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 문제3

In [4]:
# 문제3
import numpy as np
arr=np.arange(1,21)
print('마지막 원소:', arr[-1])
print('모든원소의 합:',arr.sum())
print('모든원소의 평균:',arr.mean())
new_arr=arr.reshape(4,5) # 4행 5열의 배열로 변경
print(new_arr)

마지막 원소: 20
모든원소의 합: 210
모든원소의 평균: 10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# 문제4

In [5]:
# 문제4
import numpy as np
salary=[200,150,180,220,250]
new_salary=np.array(salary,dtype='float64') * 1.5
print('인상된 금액 : ',new_salary)
avg_salary=np.mean(new_salary)
print('평균 금액 : ', avg_salary)
result=new_salary>=avg_salary
print('평균이상인 원소 : ', new_salary[result])
print('평균이상인 원소의 개수 : ',new_salary[result].size)

인상된 금액 :  [300. 225. 270. 330. 375.]
평균 금액 :  300.0
평균이상인 원소 :  [300. 330. 375.]
평균이상인 원소의 개수 :  3
