# 배열생성하기

## 리스트로 배열 만들기

In [ ]:
# 1차원 배열(list)로 NumPy 배열 생성
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2차원 배열(list)로 NumPy 배열 생성
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3차원 배열(list)로 NumPy 배열 생성
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## 배열 생성 및 초기화

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
b=np.ones((3,3))
print(b)

NameError: ignored

In [ ]:
a=np.full((3,3),1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.tri(3)
print(a)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## 생성한 값으로 배열 생성

In [ ]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a=np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [ ]:
a=np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


## 랜덤(난수)으로 배열 생성하기

In [ ]:
a=np.random.random()
print(a)

0.9926324802497026


In [ ]:
a=np.random.random((4,4))
print(a)

[[0.16618881 0.7430632  0.42123286 0.76126684]
 [0.64943997 0.47765548 0.25851604 0.42963924]
 [0.88918227 0.20856945 0.84504922 0.64993751]
 [0.88676547 0.01447417 0.13687649 0.51767233]]


In [ ]:
a=np.random.randint(1,10)
print(a)

8


In [ ]:
a=np.random.randint(1,10,(4,4))
print(a)

[[3 9 9 8]
 [5 8 6 4]
 [1 5 5 3]
 [4 8 7 1]]


In [ ]:
a=np.random.rand(3,3)
print(a)

[[0.5553195  0.01618298 0.45197812]
 [0.14882833 0.6100522  0.86166301]
 [0.59679469 0.29181243 0.71931686]]


In [ ]:
a=np.random.randn(3,3)
print(a)

[[-1.76838018  0.14220598 -1.31978749]
 [-0.98732383  0.65894694  0.09234664]
 [ 1.26284942  1.13236587 -1.12411091]]


# 배열 조회

## 배열 속성 정보

In [ ]:
arr=np.arange(1,6)
print(arr)
print('ndim:',arr.ndim)  
print('shape:',arr.shape) 
print('dtype:',arr.dtype) 
print('size:',arr.size) 
print('itemsize:',arr.itemsize) 
print('nbytes:',arr.nbytes) 

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40


## 배열인덱싱 및 슬라이싱

In [ ]:
import numpy as np

In [ ]:
a1 = np.arange(9) # 1차원 배열
print(a1)
print(a1[0])
print(a1[-1])
a1[0]=10 # 요소변경
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [ ]:
a2 = np.arange(9).reshape((3, 3)) #2차원 배열
print(a2)
print(a2[0,1]) # 1행 두번째 컬럼 요소 참조
print(a2[1,2]) # 2행 세번째 컬럼 요소 참조
a2[0,0]=10 # 1행 첫번째 컬럼 업데이트
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [ ]:
a1= np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2])
print(a1[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [ ]:
a2 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
print(a2)
print(a2[1])
print(a2[1:3,1:5])
print(a2[2,:])
print(a2[:3,:3])
print(a2[2:,::-1])
print(a2[::-1,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


## 불리언 인덱싱

In [ ]:
a=np.arange(1,6)
print(a)
b=[True,False,False,True,False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [ ]:
a=np.arange(11)
print(a[a<5])
five_up=(a>=5)
five_up
print(a[five_up])
divide_by_2=a[a%2==0]
print(divide_by_2)

[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [ ]:
# 논리연산자 사용( &, | ~)
c = a[(a > 5) & (a < 11)] # and
print(c)
d=a[(a > 9) | (a < 5)]  # or
print(d)
e=a[~(a%3==0)] # not
print(e)

[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


# 배열연산

## 산술연산

In [ ]:
a=np.arange(1,11)
b=np.arange(1,11)
print(a+b)
print(np.add(a,b)) # 덧셈함수
print(a-b)
print(np.subtract(a,b)) # 뺄셈함수
print(a*b)
print(np.multiply(a,b)) # 곱셈함수
print(a/b)
print(np.divide(a,b)) # 나눗셈함수

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a=np.arange(1,11)
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
# 합계 : [ndarray 배열 객체].sum(), np.sum()
a=np.arange(1,10).reshape(3,3)
print(a.sum())
print(np.sum(a))
print(a)
b=a.sum(axis=0)
print(b)
c=a.sum(axis=1)
print(c)

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [ ]:
# 최대값 : [ndarray 배열 객체].max(), np.max()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.max(),np.max(a))
print(a.max(axis=0), np.max(a,axis=0))
print(a.max(axis=1),np.max(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


In [ ]:
# 최소값 : [ndarray 배열 객체].min(), np.min()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.min(),np.min(a))
print(a.min(axis=0), np.min(a,axis=0))
print(a.min(axis=1),np.min(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 1
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [ ]:
# 평균과 중앙값
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.mean(),np.mean(a))
print(a.mean(axis=0),np.mean(a,axis=0))
print(a.mean(axis=1),np.mean(a,axis=1))
print(np.median(a)) # 중앙값

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]
5.0


In [ ]:
# 표준편차
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.std(), np.std(a))
print(a.std(axis=0), np.std(a,axis=0))
print(a.std(axis=1), np.std(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


In [ ]:
# 브로드캐스팅 사용하지 않은 경우
x=np.array([1,2,3,4,5])
y=np.array([1,1,1,1,1])
print(x+y)
# 브로드캐스팅을 사용한 경우
y=1
print(x+y)

[2 3 4 5 6]
[2 3 4 5 6]


In [ ]:
a=np.arange(1,25).reshape(4,6)
print(a+100) # 브로드캐스팅

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
# step1 : 스칼라 배열 변경
new_arr=np.full_like(a,100)
print(new_arr)
# step2 : 배열 이항 연산
print(a+new_arr)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
a = np.arange(5).reshape((1, 5))
print(a)
b = np.arange(5).reshape((5, 1))
print(b)
print(a+b) # 브로드캐스팅

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [ ]:
import numpy as np
import time

a = np.arange(10000000)
result = 0
s=time.time()
for v in a:
  result += v
e=time.time()
print(result, e-s) # 
s=time.time()
result=np.sum(a)
e=time.time()
print(result, e-s) # 백터연산 

49999995000000 3.0021324157714844
49999995000000 0.010520219802856445


# 배열변환

## 전치행렬

In [ ]:
a = np.random.randint(1,10,(3,3))
print(a)
print(a.T) # 전치행렬

[[8 3 9]
 [5 9 8]
 [7 3 9]]
[[8 5 7]
 [3 9 3]
 [9 8 9]]


## 배열형태 변환

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.ravel()
b=a.ravel()
b[0]=10
print(b)
print(a) # b 배열 변경이 a 행렬에 반영됨

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [ ]:
x=np.arange(20)
y=x.reshape(4,5)
print(y)
x[0]=10
print(x)
print(y) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
list_data = [1,2,3,4,5,6]
list_data.reshape(3,2)


AttributeError: ignored

In [ ]:
list_data = [1,2,3,4,5,6]
#list_data.reshape(3,2)
data=np.array(list_data)
type(data)
print(data.reshape(3,2))
print(list_data)

[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

## 배열 요소 추가/삭제

In [ ]:
x=np.arange(20)
y=np.resize(x,(5,4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
x=np.arange(20)
y=np.resize(x,(5,6))
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9]])

In [ ]:
x=np.arange(20)
y=np.resize(x,(5,3))
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
x=np.arange(20)
y=np.resize(x,(4,5))
print(y)
x[0]=10
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
a = np.arange(3)
b = np.append(a, 3)
print(b)

[0 1 2 3]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# 축 지정하기
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])
c = np.append(a, b, axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# insert 함수
a = np.array([1, 2, 3])
b = np.insert(a, 1, 5)

print(a)
print(b)

[1 2 3]
[1 5 2 3]


In [ ]:
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.insert(a, 1, 5)
print(a)
print(b)

[[1 1]
 [2 2]
 [3 3]]
[1 5 1 2 2 3 3]


In [ ]:
# 축 지정하기
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.insert(a, 1, 5, axis=0)
c = np.insert(a, 1, 5, axis=1)
print(a)
print(b)
print(c)

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [5 5]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 5 2]
 [3 5 3]]


In [ ]:
# 값 삭제하기
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a, 5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]


In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a, 1, axis=0))
print(np.delete(a, 1, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


## 배열결합하기

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
arr = np.concatenate((a1, a2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, 5, 6]])
axis0 = np.concatenate((a1, a2), axis=0)
axis1 = np.concatenate((a1, a2), axis=1)
print(axis0)
print(axis1)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [ ]:
# 수직 방향 배열 결합
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 수평 방향 배열 결합
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.arange(16).reshape(4, 4)
a_hsplit = np.hsplit(a, 2)
print(a)
print(a_hsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
a = np.arange(16).reshape(4, 4)
a_vsplit = np.vsplit(a, 2)
print(a)
print(a_vsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
